### ISSUE TITLE
Required indicator for required furo.Reference

### ISSUE THREAD

**Issue by MarcOmlin** [theNorstroem/furo-ui5#45]
I defined  its_artikel as a *furo.Reference field in my muspec and also checked the generated specs if its required and this is all good.
But furo-ui5-reference-search does not show the red star and also does not provide client side error messages for this required field.

Muspec definition:
```
    display_user: 'string:5 #display_name vom User'
    its_artikel: |-
        * furo.Reference:13 = {
        	"link": {
        		"rel": "list",
        		"href": "/artikel",
        		"method": "GET",
        		"type": "artikel.Artikel",
        		"service": "Services.artikelservice.Artikel"
        	}
        }
         #Artikel Referenz
    menge: '* float:2 #Menge'
    tag: '* google.type.Date:3 #Datum, an dem das Ersatzteil bestellt wurde. (Rapport-Datum)'
    ulid_lagerort: '* string:9 #Lagerort'
```

Spec-Field definition:
```
    its_artikel:
        type: furo.Reference
        description: Artikel Referenz
        __proto:
            number: 13
        __ui: null
        meta:
            default: |-
                {
                	"link": {
                		"rel": "list",
                		"href": "/artikel",
                		"method": "GET",
                		"type": "artikel.Artikel",
                		"service": "Services.artikelservice.Artikel"
                	}
                }
            placeholder: ersatzteil.ersatzteil.itsartikel.placeholder
            hint: ""
            label: ersatzteil.ersatzteil.itsartikel.label
            options:
                flags: []
                list: []
            readonly: false
            repeated: false
            typespecific: null
        constraints:
            required:
                is: "true"
                message: ersatzteil.ersatzteil.itsartikel.constraint.required.message
    menge:
        type: float
        description: Menge
        __proto:
            number: 2
        __ui: null
        meta:
            default: ""
            placeholder: ersatzteil.ersatzteil.menge.placeholder
            hint: ""
            label: ersatzteil.ersatzteil.menge.label
            options:
                flags: []
                list: []
            readonly: false
            repeated: false
            typespecific: null
        constraints:
            required:
                is: "true"
                message: ersatzteil.ersatzteil.menge.constraint.required.message
    tag:
        type: google.type.Date
        description: Datum, an dem das Ersatzteil bestellt wurde. (Rapport-Datum)
        __proto:
            number: 3
        __ui: null
        meta:
            default: ""
            placeholder: ersatzteil.ersatzteil.tag.placeholder
            hint: ""
            label: ersatzteil.ersatzteil.tag.label
            options:
                flags: []
                list: []
            readonly: false
            repeated: false
            typespecific: null
        constraints:
            required:
                is: "true"
                message: ersatzteil.ersatzteil.tag.constraint.required.message
```

Display in the Client:
<img width="900" alt="Screenshot at Apr 27 16-33-30" src="https://user-images.githubusercontent.com/42028916/165543049-72faa892-1289-4f4d-af8b-3d28c6499e6e.png">

How can i fix this issue? Can u give me any advice?

Thx for your good work 👍
